export const DISMISS_MESSAGE = 'DISMISS_MESSAGE';

export const CREATE_REQUEST = 'CREATE_REQUEST';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const REQUEST_FAILURE = 'REQUEST_FAILURE';

export const CREATE_TOPIC_REQUEST = 'CREATE_TOPIC_REQUEST';
export const CREATE_TOPIC_FAILURE = 'CREATE_TOPIC_FAILURE';
export const CREATE_TOPIC_SUCCESS = 'CREATE_TOPIC_SUCCESS';
export const CREATE_TOPIC_DUPLICATE = 'CREATE_TOPIC_DUPLICATE';
export const GET_TOPICS = 'GET_TOPICS';
export const GET_TOPICS_REQUEST = 'GET_TOPICS_REQUEST';
export const GET_TOPICS_SUCCESS = 'GET_TOPICS_SUCCESS';
export const GET_TOPICS_FAILURE = 'GET_TOPICS_FAILURE';
export const INCREMENT_COUNT = 'INCREMENT_COUNT';
export const DECREMENT_COUNT = 'DECREMENT_COUNT';
export const DESTROY_TOPIC = 'DESTROY_TOPIC';

export const TOGGLE_LOGIN_MODE = 'TOGGLE_LOGIN_MODE';
export const MANUAL_LOGIN_USER = 'MANUAL_LOGIN_USER';
export const LOGIN_SUCCESS_USER = 'LOGIN_SUCCESS_USER';
export const LOGIN_ERROR_USER = 'LOGIN_ERROR_USER';
export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_SUCCESS_USER = 'SIGNUP_SUCCESS_USER';
export const SIGNUP_ERROR_USER = 'SIGNUP_ERROR_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_SUCCESS_USER = 'LOGOUT_SUCCESS_USER';
export const LOGOUT_ERROR_USER = 'LOGOUT_ERROR_USER';

// Games Events
export const CREATE_GAME = 'CREATE_GAME';
export const BEGIN_GAME = 'server/BEGIN_GAME';
export const GAME_STARTING = 'server/GAME_STARTING';
export const GAME_LOBBY_TICK = 'GAME_LOBBY_TICK';
export const GAME_FLIP_TICK = 'GAME_LOBBY_TICK';
export const JOIN_GAME = 'server/JOIN_GAME';
export const JOIN_GAME_SUCCESS = 'server/JOIN_GAME_SUCCESS';
export const JOIN_GAME_ERROR = 'JOIN_GAME_ERROR';
export const NOT_ENOUGH_BALANCE = 'NOT_ENOUGH_BALANCE';

export const ADD_MESSAGE = 'server/ADD_MESSAGE';
export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE';

export const LOAD_MESSAGES = 'LOAD_MESSAGES';
export const LOAD_MESSAGES_SUCCESS = 'LOAD_MESSAGES_SUCCESS';
export const LOAD_MESSAGES_FAIL = 'LOAD_MESSAGES_FAIL';
export const RECEIVE_MESSAGES = 'RECEIVE_MESSAGES';



// Account Actions
export const WITHDRAWAL_REQUEST_BEGIN = 'WITHDRAWAL_REQUEST_BEGIN';
export const WITHDRAWAL_REQUEST_SUCCESS = 'WITHDRAWAL_REQUEST_SUCCESS';
export const WITHDRAWAL_REQUEST_FAILURE = 'WITHDRAWAL_REQUEST_FAILURE';

export const UPDATE_USER_BALANCE = 'UPDATE_USER_BALANCE';


export const ADD_CHANNEL = 'ADD_CHANNEL';
export const CHANGE_CHANNEL = 'CHANGE_CHANNEL';
export const RECEIVE_CHANNEL = 'RECEIVE_CHANNEL';

export const LOAD_CHANNELS = 'LOAD_CHANNELS';
export const LOAD_CHANNELS_SUCCESS  = 'LOAD_CHANNELS_SUCCESS';
export const LOAD_CHANNELS_FAIL = 'LOAD_CHANNELS_FAIL';

export const TYPING = 'TYPING';
export const STOP_TYPING = 'STOP_TYPING';